ckpt_base_path: /home/minghao/workspace/dino_wm
training:
  seed: 0
  epochs: 1
  batch_size: 4
  save_every_x_epoch: 1
  reconstruct_every_x_batch: 500
  num_reconstruct_samples: 2
  encoder_lr: 1.0e-06
  decoder_lr: 0.0003
  predictor_lr: 0.0005
  action_encoder_lr: 0.0005
img_size: 224
frameskip: 5
concat_dim: 1
normalize_action: true
action_emb_dim: 16
num_action_repeat: 1
proprio_emb_dim: 32
num_proprio_repeat: 1
num_hist: 3
num_pred: 1
has_predictor: true
has_decoder: true
model:
  _target_: models.visual_world_model.VWorldModel
  image_size: 224
  num_hist: 3
  num_pred: 1
  train_encoder: false
  train_predictor: true
  train_decoder: true
debug: true
plan_settings:
  plan_cfg_path: null
  planner:
  - gd
  goal_source:
  - dset
  goal_H:
  - 5
  alpha:
  - 0.1
env:
  name: robomimic_can
  args: []
  kwargs:
    with_velocity: true
    with_target: true
  dataset:
    _target_: datasets.robomimic_dset.load_robomimic_slice_train_val
    with_velocity: true
    n_rollout: null
    normalize_action: true
    data_path: /mnt/data1/minghao/robomimic/can/ph_converted_final
    split_ratio: 0.9
    transform:
      _target_: datasets.img_transforms.default_transform
      img_size: 224
  decoder_path: null
  num_workers: 16
encoder:
  _target_: models.dino.DinoV2Encoder
  name: dinov2_vits14
  feature_key: x_norm_patchtokens
  projected_dim: 128
action_encoder:
  _target_: models.proprio.ProprioceptiveEmbedding
  num_frames: 1
  tubelet_size: 1
  use_3d_pos: false
proprio_encoder:
  _target_: models.proprio.ProprioceptiveEmbedding
  num_frames: 1
  tubelet_size: 1
  use_3d_pos: false
decoder:
  _target_: models.vqvae.VQVAE
  channel: 384
  n_embed: 2048
  n_res_block: 4
  n_res_channel: 128
  quantize: false
predictor:
  _target_: models.vit.ViTPredictor
  depth: 6
  heads: 16
  mlp_dim: 2048
  dropout: 0.1
  emb_dropout: 0
  pool: mean
saved_folder: /home/minghao/workspace/dino_wm
effective_batch_size: 4
gpu_batch_size: 4
wandb_run_id: e5wdmftg
