# Proprioceptive-only planning config
defaults:
  - _self_

hydra:
  run:
    dir: plan_outputs/${now:%Y%m%d%H%M%S}_proprio_planning_gH${goal_H}

# No model checkpoint needed for proprio-only planning
ckpt_base_path: /home/minghao/workspace/dino_wm
model_name: "proprio_only_dummy"
model_epoch: latest

seed: 99
n_evals: 50
goal_source: 'dset'
goal_H: 5 
n_plot_samples: 10

debug_dset_init: False

objective:
  _target_: planning.objectives.create_objective_fn
  alpha: 1
  base: 2
  mode: last

planner:
  _target_: planning.mpc.MPCPlanner
  max_iter: null 
  n_taken_actions: 5
  sub_planner:
    target: planning.cem.CEMPlanner
    horizon: 5
    topk: 30
    num_samples: 300
    var_scale: 1
    opt_steps: 30
    eval_every: 1
  name: mpc_cem