# @package _global_
defaults:
  - _self_
  - train_robomimic_align_with_recon

# Override alignment settings for MLP mapping experiments  
alignment:
  state_consistency_loss_weight: 1.0
  alignment_regularization: 0.01
  dynamics_7d_loss_weight: 1.0  # Enable 7D dynamics loss
  dynamic_ratio: 1.0  # All 7 dims are dynamic
  alignment_feature_selection: 'mapping'  # Use MLP to map full dims to 64

# Update wandb project name
wandb:
  project: dino_wm_7d_mapping
  name: "7d_dynamics_${alignment.alignment_feature_selection}_ratio_${alignment.dynamic_ratio}"