# Configuration for training with alignment + reconstruction (NO 7D temporal dynamics loss)
defaults:
  - train_robomimic_align_with_recon
  - _self_

# Alignment configuration WITHOUT 7D temporal dynamics loss
alignment:
  state_consistency_loss_weight: 1.0    # Weight for alignment loss
  alignment_regularization: 0.01        # L2 regularization on alignment matrix W
  dynamics_7d_loss_weight: 0.0          # 7D temporal dynamics loss DISABLED

# WandB project name
wandb:
  project: dino_wm_align_recon_no_dynamics
  name: robomimic_can_align_recon_no_dynamics_f5_h3_p1

# Training settings
training:
  total_epochs: 100
  save_every_x_epoch: 5