name: robomimic_can_original
dataset:
  _target_: "datasets.robomimic_dset_original.load_robomimic_slice_train_val_original"
  with_velocity: true
  n_rollout: null
  normalize_action: ${normalize_action}
  data_path: /home/ubuntu/minghao/data/robomimic/can/ph_convert  # 7D dataset
  split_ratio: 0.9
  num_hist: ${num_hist}
  num_pred: ${num_pred}
  frameskip: ${frameskip}
  transform:
    _target_: "datasets.img_transforms.default_transform"
    img_size: ${img_size}