_target_: models.vqvae.VQVAE
channel: 64  # Internal processing channels  
n_embed: 2048
n_res_block: 4
n_res_channel: 128
quantize: False
emb_dim: ${projected_dim}  # Input dimension same as projected_dim