_target_: models.hierarchical_projector.HierarchicalProjector
in_features: ${projection_input_dim}  # computed in train.py
out_features: ${projected_dim}  # 64
input_patches: 196  # 14x14 DINO patches
output_patches: 49  # 7x7 compressed patches
num_layers: 3
hidden_dim: 256
use_cross_attention: true