# Temporal Projector Configuration for Robomimic
# 处理 z_{t-1} + x_t -> z_t 的时序投影 (Robomimic维度)

_target_: models.temporal_projector.TemporalProjector

# Input dimensions for Robomimic
# in_features and out_features will be passed dynamically at runtime
num_hist: 3          # 使用前3个历史z states作为输入
z_patches: 196       # z_{t-i} patch数量 (14x14, NO compression)
z_dim: 64            # z_{t-i} feature维度 (64)
x_patches: 196       # x_t patch数量 (14x14, DINO patches)

# Output dimensions
output_patches: 196  # 输出patch数量 (14x14, NO compression)

# ViT architecture parameters
hidden_dim: 256      # 共同的hidden维度
depth: 4             # Transformer层数
heads: 8             # Attention头数
mlp_dim: 1024        # MLP隐藏维度
dim_head: 32         # 每个attention head的维度
dropout: 0.1         # Dropout率
emb_dropout: 0.1     # Embedding dropout率